import type { Deal } from "@/lib/deals";
import type { Database } from "@/lib/supabase/types";

type DealRow = Database["public"]["Tables"]["deals"]["Row"];

export function mapDealRow(row: DealRow): Deal {
  return {
    id: row.id,
    title: row.title,
    location: row.location,
    region: row.region,
    assetType: row.asset_type as Deal["assetType"],
    source: row.source as Deal["source"],
    guidePrice: row.guide_price,
    passingRent: row.passing_rent,
    sqft: row.sqft,
    grossYield: row.gross_yield,
    netInitialYield: row.net_initial_yield,
    reversionaryYield: row.reversionary_yield,
    wault: row.wault,
    leaseLength: row.lease_length,
    tenant: row.tenant,
    covenantStrength: row.covenant_strength as Deal["covenantStrength"],
    tenantHealthScore: row.tenant_health_score,
    rentSustainability: row.rent_sustainability as Deal["rentSustainability"],
    rentReview: row.rent_review as Deal["rentReview"],
    pricePerSqft: row.price_per_sqft,
    planningUpsideScore: row.planning_upside_score,
    voidRiskScore: row.void_risk_score,
    exitYieldSensitivity: row.exit_yield_sensitivity as Deal["exitYieldSensitivity"],
    cashflowAfterDebt: row.cashflow_after_debt,
    returnOnEquity: row.return_on_equity,
    auctionGuideRisk: row.auction_guide_risk as Deal["auctionGuideRisk"],
    redFlags: row.red_flags ?? [],
    mainRiskFlag: row.main_risk_flag,
    score: row.score,
    rating: row.rating as Deal["rating"],
    scoreBreakdown: row.score_breakdown as Deal["scoreBreakdown"],
    insights: row.insights as Deal["insights"],
    thumbnail: row.thumbnail,
    postedAt: row.posted_at,
  };
}

export function mapDealToInsert(deal: Deal) {
  return {
    id: deal.id,
    title: deal.title,
    location: deal.location,
    region: deal.region,
    asset_type: deal.assetType,
    source: deal.source,
    guide_price: deal.guidePrice,
    passing_rent: deal.passingRent,
    sqft: deal.sqft,
    gross_yield: deal.grossYield,
    net_initial_yield: deal.netInitialYield,
    reversionary_yield: deal.reversionaryYield,
    wault: deal.wault,
    lease_length: deal.leaseLength,
    tenant: deal.tenant,
    covenant_strength: deal.covenantStrength,
    tenant_health_score: deal.tenantHealthScore,
    rent_sustainability: deal.rentSustainability,
    rent_review: deal.rentReview,
    price_per_sqft: deal.pricePerSqft,
    planning_upside_score: deal.planningUpsideScore,
    void_risk_score: deal.voidRiskScore,
    exit_yield_sensitivity: deal.exitYieldSensitivity,
    cashflow_after_debt: deal.cashflowAfterDebt,
    return_on_equity: deal.returnOnEquity,
    auction_guide_risk: deal.auctionGuideRisk ?? null,
    red_flags: deal.redFlags,
    main_risk_flag: deal.mainRiskFlag,
    score: deal.score,
    rating: deal.rating,
    score_breakdown: deal.scoreBreakdown,
    insights: deal.insights,
    thumbnail: deal.thumbnail,
    posted_at: deal.postedAt,
  };
}
