export const OFFICIAL_ENGLISH_CITIES = [
  "Bath",
  "Birmingham",
  "Bradford",
  "Brighton and Hove",
  "Bristol",
  "Cambridge",
  "Canterbury",
  "Carlisle",
  "Chelmsford",
  "Chester",
  "Chichester",
  "Colchester",
  "Coventry",
  "Derby",
  "Doncaster",
  "Durham",
  "Ely",
  "Exeter",
  "Gloucester",
  "Hereford",
  "Kingston upon Hull",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Lichfield",
  "Lincoln",
  "Liverpool",
  "London",
  "Manchester",
  "Milton Keynes",
  "Newcastle upon Tyne",
  "Norwich",
  "Nottingham",
  "Oxford",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Ripon",
  "Salford",
  "Salisbury",
  "Sheffield",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "Stoke-on-Trent",
  "Sunderland",
  "Truro",
  "Wakefield",
  "Wells",
  "Westminster",
  "Winchester",
  "Wolverhampton",
  "Worcester",
  "York",
];

export const MAJOR_ENGLISH_COMMERCIAL_TOWNS = [
  "Aldershot",
  "Ashford",
  "Aylesbury",
  "Barnsley",
  "Barnstaple",
  "Basildon",
  "Basingstoke",
  "Bedford",
  "Birkenhead",
  "Blackburn",
  "Blackpool",
  "Bolton",
  "Bootle",
  "Bournemouth",
  "Bracknell",
  "Burnley",
  "Burton upon Trent",
  "Bury",
  "Cheltenham",
  "Chesterfield",
  "Corby",
  "Crawley",
  "Crewe",
  "Croydon",
  "Darlington",
  "Dudley",
  "Eastbourne",
  "Ellesmere Port",
  "Fareham",
  "Folkestone",
  "Gateshead",
  "Gillingham",
  "Grimsby",
  "Guildford",
  "Halifax",
  "Harrogate",
  "Hartlepool",
  "Hemel Hempstead",
  "High Wycombe",
  "Huddersfield",
  "Ipswich",
  "Kettering",
  "Kingston upon Thames",
  "Luton",
  "Maidstone",
  "Mansfield",
  "Middlesbrough",
  "Northampton",
  "Nuneaton",
  "Oldham",
  "Poole",
  "Reading",
  "Redditch",
  "Rochdale",
  "Rotherham",
  "Scunthorpe",
  "Slough",
  "Solihull",
  "Southport",
  "St Helens",
  "Stockport",
  "Swindon",
  "Telford",
  "Torquay",
  "Walsall",
  "Warrington",
  "Watford",
  "Wigan",
  "Woking",
  "Worthing",
  "Yeovil",
];

export const ENGLAND_REGIONAL_SEARCH_AREAS = [
  "Berkshire",
  "Buckinghamshire",
  "Cambridgeshire",
  "Cheshire",
  "Cornwall",
  "Cumbria",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Essex",
  "Gloucestershire",
  "Greater Manchester",
  "Hampshire",
  "Hertfordshire",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Merseyside",
  "Norfolk",
  "North Yorkshire",
  "Northamptonshire",
  "Nottinghamshire",
  "Oxfordshire",
  "Somerset",
  "Staffordshire",
  "Suffolk",
  "Surrey",
  "Sussex",
  "Tyne and Wear",
  "Warwickshire",
  "West Midlands",
  "West Yorkshire",
  "Wiltshire",
];

export const ENGLAND_NATIONAL_SCAN_LOCATIONS = uniqueLocations([
  ...OFFICIAL_ENGLISH_CITIES,
  ...MAJOR_ENGLISH_COMMERCIAL_TOWNS,
  ...ENGLAND_REGIONAL_SEARCH_AREAS,
]);

function uniqueLocations(locations) {
  const seen = new Set();
  const result = [];
  for (const location of locations) {
    const key = String(location).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    result.push(location);
  }
  return result;
}
